version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      cloudflare:
        patterns:
          - "wrangler"
          - "@cloudflare/*"
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - "wrangler"
          - "@cloudflare/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
