/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b1b9df00a67e9a9d98eadb2ec49770bc)
interface __BaseEnv_Env {
	DB: D1Database;
	CORRECTION_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
